export enum StagesState {
  ON_HOLD = 'on-hold',
  START = 'start',
  WEEK_1 = 'week-1',
  WEEK_2 = 'week-2',
  WEEK_3 = 'week-3',
  WEEK_4 = 'week-4',
  WEEK_5 = 'week-5',
  WEEK_6 = 'week-6',
  WEEK_7 = 'week-7',
  WEEK_8 = 'week-8',
  WEEK_9 = 'week-9',
  DENIED = 'denied',
  ACCEPTED = 'accepted',
}
