version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root      
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    env_file:
      - docker.env

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hiring_manager
    ports:
      - "5432:5432"
    env_file:
      - docker.env
